  language: python
  python:
    - 3.6
  matrix:
    include:
      - python: 3.7
        dist: xenial
        sudo: true
  install:
    - pip install -r requirements/test.txt
    - pip install -e .
  script:
    - behave tests/features
    - pytest
