"""empty message

Revision ID: dd56f65eac48
Revises: 
Create Date: 2019-09-09 13:17:13.916677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd56f65eac48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=140), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_text',
    sa.Column('current_text', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_text'], ['text.id'], )
    )
    op.create_table('next_texts',
    sa.Column('current_text', sa.Integer(), nullable=True),
    sa.Column('next_text', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_text'], ['text.id'], ),
    sa.ForeignKeyConstraint(['next_text'], ['text.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('next_texts')
    op.drop_table('current_text')
    op.drop_table('text')
    # ### end Alembic commands ###
