"""empty message

Revision ID: 4a4148517b06
Revises: 447d0209e726
Create Date: 2019-02-10 11:02:00.372677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4148517b06'
down_revision = '447d0209e726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'created')
    # ### end Alembic commands ###
